### ISSUE TITLE
Different colors than the VSCode theme

### ISSUE THREAD

**Issue by alexventuraio** [phanviet/vim-monokai-pro#11]
How can I get the same colors as in the VSCode them?

I see a couple of differences specially in the `(){}[]'</>` and in some words like the ones in line 8 and 9.
Is is possible to change `()` colors as they are nested like in the `catch` statement in line 23 on the left?

> I have already installed `sheerun/vim-polyglot`

![Screen Shot 2020-11-04 at 13 32 05](https://user-images.githubusercontent.com/13169164/98160042-399c9e00-1ea3-11eb-952d-149a7eb90479.png)

![Screen Shot 2020-11-04 at 13 37 42](https://user-images.githubusercontent.com/13169164/98159967-170a8500-1ea3-11eb-9a24-550a2fb44fe4.png)

**Comment by phanviet** [comment]
Hi, for nested brackets diff color, you can use https://github.com/luochen1990/rainbow .

**Comment by phanviet** [comment]
Updated Ruby symbol and instance variable color to purple. For others, it can't reach to VS Code for now.
