### ISSUE TITLE
Color difference between Vim8 and NeoVim

### ISSUE THREAD

**Issue by kaykhancheckpoint** [phanviet/vim-monokai-pro#13]
Hi,

I noticed there is a color differnece whne using this theme on vim8 vs neovim.

**Vim8**
![image](https://user-images.githubusercontent.com/65535942/121517114-e1a0b980-c9e6-11eb-8f1e-59e712fb47cd.png)

**Neovim**
![image](https://user-images.githubusercontent.com/65535942/121517140-ea918b00-c9e6-11eb-8c14-828cfa059100.png)

Can anyone help i do prefer `import` statements being red instead of purple(neovim).

**Comment by nikkolai14** [comment]
Hi,

I am using neovim v0.6.0 and it was working fine on my end.

![image](https://user-images.githubusercontent.com/27313654/144873809-a67bee65-e373-470c-9c68-714a682dda07.png)

**Comment by phanviet** [comment]
Fixed. Thanks all.
