### ISSUE TITLE
Lightline support

### ISSUE THREAD

**Issue by hjetmundsen** [phanviet/vim-monokai-pro#4]
# Feature Request

Do you have plans of adding support for Lightline in the future? I'm currently just using the molokai Lightline theme but it feels out of place.

**Comment by phanviet** [comment]
@henryjetmundsen I'm happy to see you interesting with my porting. Lightline is also nice looking, I will add it into my plan and update soon. Thank you.

**Comment by fr3fou** [comment]
Any news?
