### ISSUE TITLE
the color scheme is not applying all the colors

### ISSUE THREAD

**Issue by Shinkei** [phanviet/vim-monokai-pro#5]
Hi, this is my first time using a theme for vim, I have done all the steps you describe on the Readme, but I cannot see all the colors for this theme.
can you help me?

![image](https://user-images.githubusercontent.com/348883/53701886-8c20df80-3dcf-11e9-975b-b3077a0992a9.png)

**Comment by phanviet** [comment]
@Shinkei 
You might need install: https://github.com/sheerun/vim-polyglot to have better syntax highlight.
